name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: CaltechOpticalObservatories/camera-interface/.github/workflows/instrument-ci.yml@main
